basic.forever(function () {
    music.playMelody("A C A C D A C A ", 433)
    music.playMelody("A C A C D A C A ", 433)
    music.playMelody("A C A C D A C A ", 433)
    music.playMelody("A C A C D A C A ", 433)
    music.playMelody("A C A C D A C A ", 433)
    music.playMelody("A C A C D A C A ", 433)
    music.playMelody("A C A C D A C A ", 433)
    music.playMelody("A C A C D A C A ", 433)
    music.playMelody("A C A C D A C A ", 433)
    music.playMelody("A C A C D A C A ", 433)
    music.playMelody("A C A C D A C A ", 433)
    music.playMelody("A C A C D A C A ", 433)
    music.playMelody("A C A C D A C A ", 433)
})
