def on_forever():
    music.play_melody("A C A C D A C A ", 433)
    music.play_melody("A C A C D A C A ", 433)
    music.play_melody("A C A C D A C A ", 433)
    music.play_melody("A C A C D A C A ", 433)
    music.play_melody("A C A C D A C A ", 433)
    music.play_melody("A C A C D A C A ", 433)
    music.play_melody("A C A C D A C A ", 433)
    music.play_melody("A C A C D A C A ", 433)
    music.play_melody("A C A C D A C A ", 433)
    music.play_melody("A C A C D A C A ", 433)
    music.play_melody("A C A C D A C A ", 433)
    music.play_melody("A C A C D A C A ", 433)
    music.play_melody("A C A C D A C A ", 433)
basic.forever(on_forever)
